### ISSUE TITLE
ENS should be disabled by default

### ISSUE THREAD

**Issue by rht** [pelith/node-eauth-server#21]
Since ENS is an optional dependency, https://github.com/pelith/node-eauth-server/blob/2604c707e38d4f63d82f15a18d36ff55b2c4eb10/.env.example#L11 should be false by default.

**Comment by hung-pelith** [comment]
I think we should keep it true because the optional dependencies will be installed by default, so the developers can see the full demo.

**Comment by rht** [comment]
Ah, gotcha. `yarn install` by default installs the optional dependencies.
