### ISSUE TITLE
.env.example should contain comments as found in README.md

### ISSUE THREAD

**Issue by rht** [pelith/node-eauth-server#22]
E.g. 
```
# your brand name
EAUTH_BANNER=YOUR_BANNER_HERE
# morgan logger
EAUTH_LOGGING=true
```
This is so that users can see the context for the variables on the spot, inside the .env.example file.
To avoid duplication, maybe the config text in README.md should be removed instead.

**Comment by hung-pelith** [comment]
I'll take your advice.
