### ISSUE TITLE
Unresponsiveness when logging in (requires second click sometimes)

### ISSUE THREAD

**Issue by FantasticoFox** [pelith/node-eauth-server#23]
probably because of long load time.

![Selection_051](https://user-images.githubusercontent.com/45313235/132681218-e1aa4eee-8af2-4af6-abc6-c50cf610b1e3.png)

**Comment by hung-pelith** [comment]
Thanks for your comment, I'll improve the UX.

**Comment by hung-pelith** [comment]
The button will be disabled and showing a waiting curser when it's still loading currently.

**Comment by FantasticoFox** [comment]
Thank you for the fast fix & improvement!

**Comment by rht** [comment]
I think the container hasn't been updated yet? I'm still experiencing this issue even after a `docker-compose pull`.

**Comment by hung-pelith** [comment]
I updated it currently, please try it again.

rht ***@***.***> 於 2021年9月15日 週三 下午2:09寫道：

**Comment by rht** [comment]
It works now! :tada:
